/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eletronico;

import eletronico.model.controller.CategoriaController;
import eletronico.model.controller.MarcaController;
import eletronico.model.controller.ProdutoController;
import eletronico.model.entidade.Categoria;
import eletronico.model.entidade.Marca;
import eletronico.model.entidade.Produto;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author suely
 */
public class CadastrarProduto extends javax.swing.JFrame {
    String id = "";
    /**
     * Creates new form CadastrarMarca
     */
    public CadastrarProduto() {
        initComponents();
        CaixaCategoria.removeAllItems();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        CategoriaController catController = new CategoriaController();
        List<Categoria> listaCategoria = catController.listar("");
        for (Categoria c : listaCategoria){
            model.addElement(new ComboItem(Integer.toString(c.getCodCategoria()), c.getNome()));
        }
        CaixaCategoria.setModel(model);
        
         CaixaMarca.removeAllItems();
        DefaultComboBoxModel marca = new DefaultComboBoxModel();
        MarcaController marController = new MarcaController();
        List<Marca> listaMarca = marController.listar("");
        for (Marca m : listaMarca){
            marca.addElement(new ComboItem(Integer.toString(m.getCodMarca()), m.getNome()));
        }
        CaixaMarca.setModel(marca);
        
        
    }
    
    public CadastrarProduto(String id){
        initComponents();
        ProdutoController Controller = new ProdutoController ();
        Produto p = Controller.BuscarProduto(id);
        
        jTextField1.setText(p.getNome());
        jTextField2.setText(String.valueOf(p.getPreco()));
        jTextField3.setText(String.valueOf(p.getQuantidade()));
        
        CaixaCategoria.removeAllItems();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        CategoriaController catController = new CategoriaController();
        List<Categoria> listaCategoria = catController.listar("");
        for (Categoria c : listaCategoria){
            model.addElement(new ComboItem(Integer.toString(c.getCodCategoria()), c.getNome()));
        }
        CaixaCategoria.setModel(model);
        
         CaixaMarca.removeAllItems();
        DefaultComboBoxModel marca = new DefaultComboBoxModel();
        MarcaController marController = new MarcaController();
        List<Marca> listaMarca = marController.listar("");
        for (Marca m : listaMarca){
            marca.addElement(new ComboItem(Integer.toString(m.getCodMarca()), m.getNome()));
        }
        CaixaMarca.setModel(marca);
          
        CaixaCategoria.getModel().setSelectedItem( new ComboItem( 
            Integer.toString(p.getCategoria().getCodCategoria()), 
                p.getCategoria().getNome() ));
        
        CaixaMarca.getModel().setSelectedItem( new ComboItem( 
            Integer.toString(p.getMarca().getCodMarca()), 
                p.getMarca().getNome() ));
        
        this.id = String.valueOf(p.getCodProduto());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CaixaCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        CaixaMarca = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        jLabel1.setText("Nome do produto:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Preço:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade:");

        jLabel4.setText("Categoria:");

        CaixaCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CaixaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaCategoriaActionPerformed(evt);
            }
        });

        jLabel5.setText("Marca:");

        CaixaMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Cadastrar Produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CaixaCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CaixaMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CaixaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CaixaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void CaixaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaCategoriaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(id.equals("")){
        Produto obj = new Produto();
        obj.setNome(jTextField1.getText());
        obj.setPreco(Double.parseDouble(jTextField2.getText()));
        obj.setQuantidade(Integer.parseInt(jTextField3.getText()));
        Object caixa1 = CaixaCategoria.getSelectedItem();
        
        Categoria categoria = new Categoria();
        
        categoria.setCodCategoria(Integer.parseInt( ((ComboItem)caixa1).getId() ));
        categoria.setNome( ((ComboItem) caixa1).getNome() );

        obj.setCategoria( categoria );
        
        Object caixa2 = CaixaMarca.getSelectedItem();
        
        Marca marca = new Marca();
        
        marca.setCodMarca(Integer.parseInt(((ComboItem)caixa2).getId()));
        marca.setNome(((ComboItem)caixa2).getNome());
        
        obj.setMarca(marca);
        
        ProdutoController controller = new ProdutoController ();
        controller.cadastrarProduto(obj);
        
        JOptionPane.showMessageDialog(this, "Produto Cadastrado" + " com sucesso.");
        
        } else{
           
        Produto obj = new Produto();
        
        obj.setCodProduto(Integer.parseInt(id));
        obj.setNome(jTextField1.getText());
        obj.setPreco(Double.parseDouble(jTextField2.getText()));
        obj.setQuantidade(Integer.parseInt(jTextField3.getText()));
        
        Object caixa1 = CaixaCategoria.getSelectedItem();
        
        Categoria categoria = new Categoria();
        
        categoria.setCodCategoria(Integer.parseInt( ((ComboItem)caixa1).getId() ));
        categoria.setNome( ((ComboItem) caixa1).getNome() );

        obj.setCategoria( categoria );
        
        Object caixa2 = CaixaMarca.getSelectedItem();
        
        Marca marca = new Marca();
        
        marca.setCodMarca(Integer.parseInt(((ComboItem)caixa2).getId()));
        marca.setNome(((ComboItem)caixa2).getNome());
        
        obj.setMarca(marca);
        
        ProdutoController controller = new ProdutoController ();
        controller.alterarProduto(obj);  
           
        JOptionPane.showMessageDialog(this, "Produto alterado ");
        }
        
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(false);
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CaixaCategoria;
    private javax.swing.JComboBox<String> CaixaMarca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
